from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ActivityType(str, Enum):
    RUNNING = "running"
    WALKING = "walking"
    CYCLING = "cycling"
    OUTDOOR_EVENT = "outdoor_event"
    TRAVELLING = "travelling"
    FARMING = "farming"
    AGRICULTURE = "agriculture"
    CONSTRUCTION = "construction"
    MARINE_ACTIVITY = "marine_activity"
    AVIATION_BRIEFING = "aviation_briefing"
    GENERAL_OUTDOOR = "general_outdoor"


class RiskFactor(BaseModel):
    parameter: str = Field(..., description="e.g. Temperature, Wind, Rain, Heat Index, Visibility")
    value: str = Field(..., description="e.g. 36°C, 45 km/h, 85%")
    impact: str = Field(..., description="Why this presents a risk")
    severity: RiskLevel


class RiskAnalysisRequest(BaseModel):
    activity: ActivityType = ActivityType.GENERAL_OUTDOOR
    temperature: float
    feels_like: Optional[float] = None
    humidity: int
    wind_speed: float
    condition: Optional[str] = "Simulated Conditions"
    pop: Optional[float] = 0.0  # Precipitation probability
    visibility: Optional[float] = None
    target_time: Optional[str] = "Current"
    language: Optional[str] = "en"
    custom_scenario: Optional[str] = Field(None, description="Optional natural language scenario context")


class RiskAnalysisResponse(BaseModel):
    activity: str
    risk_level: RiskLevel
    score: float = Field(..., description="Calculated composite risk score (0-100)")
    factors: List[RiskFactor] = []
    explanation: str
    recommendation: str
    disclaimer: str = (
        "Advisory Notice: This risk assessment is generated by an algorithmic decision-support "
        "model for planning purposes. Prototype thresholds are not official medical or government safety standards."
    )
    source: str = "Weather Impact Intelligence Engine"
    custom_scenario: Optional[str] = None
