export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
];

export const PRESET_CITIES = [
  { name: 'Chennai', state: 'Tamil Nadu', lat: 13.0827, lon: 80.2707 },
  { name: 'Delhi', state: 'Delhi', lat: 28.6139, lon: 77.2090 },
  { name: 'Mumbai', state: 'Maharashtra', lat: 19.0760, lon: 72.8777 },
  { name: 'Bengaluru', state: 'Karnataka', lat: 12.9716, lon: 77.5946 },
  { name: 'Kolkata', state: 'West Bengal', lat: 22.5726, lon: 88.3639 },
  { name: 'Hyderabad', state: 'Telangana', lat: 17.3850, lon: 78.4867 },
];

export const ACTIVITIES = [
  { id: 'general_outdoor', label: 'General Outdoor', icon: 'Sun' },
  { id: 'running', label: 'Running / Jogging', icon: 'Footprints' },
  { id: 'walking', label: 'Walking', icon: 'Footprints' },
  { id: 'cycling', label: 'Cycling', icon: 'Bike' },
  { id: 'outdoor_event', label: 'Outdoor Event / Gathering', icon: 'Tent' },
  { id: 'travelling', label: 'Highway Travel / Transit', icon: 'Car' },
  { id: 'farming', label: 'Farming & Spraying', icon: 'Wheat' },
  { id: 'agriculture', label: 'Crop Harvesting / Irrigation', icon: 'Sprout' },
  { id: 'construction', label: 'Construction & Scaffolding', icon: 'HardHat' },
  { id: 'marine_activity', label: 'Marine / Coastal Fishing', icon: 'Anchor' },
  { id: 'aviation_briefing', label: 'Aviation Briefing', icon: 'Plane' },
];

export const UI_TRANSLATIONS = {
  en: {
    navChat: 'Chat Assistant',
    navForecast: 'Forecast',
    navWhatIf: 'What-If Impact',
    navAlerts: 'Alerts Center',
    navVerify: 'Verify Claim',
    navClimate: 'Climate Trends',
    navProviders: 'NWP & Providers',
    currentWeather: 'Current Weather',
    feelsLike: 'Feels like',
    humidity: 'Humidity',
    wind: 'Wind',
    pressure: 'Pressure',
    visibility: 'Visibility',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    searchCity: 'Search city (e.g. Chennai, Delhi, Mumbai)...',
    useGps: 'Use Current Location',
    askPlaceholder: 'Ask WeatherGPT (e.g. "Can I go running tomorrow evening?")...',
    voiceSpeak: 'Speak',
    voiceListening: 'Listening...',
    verified: 'VERIFIED',
    contradicted: 'CONTRADICTED',
    unverified: 'UNVERIFIED',
    officialWarning: 'OFFICIAL GOVERNMENT WARNING',
    systemRisk: 'SYSTEM WEATHER RISK (ALGORITHMIC)',
    disclaimer: 'Prototype thresholds are for advisory planning and are not official medical or meteorological standards.',
  },
  hi: {
    navChat: 'चैट सहायक',
    navForecast: 'पूर्वानुमान',
    navWhatIf: 'क्या-अगर प्रभाव',
    navAlerts: 'चेतावनी केंद्र',
    navVerify: 'दावा सत्यापन',
    navClimate: 'जलवायु रुझान',
    navProviders: 'प्रदाता और मॉडल',
    currentWeather: 'वर्तमान मौसम',
    feelsLike: 'महसूस होता है',
    humidity: 'आर्द्रता',
    wind: 'हवा',
    pressure: 'दबाव',
    visibility: 'दृश्यता',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    searchCity: 'शहर खोजें (जैसे चेन्नई, दिल्ली, मुंबई)...',
    useGps: 'वर्तमान स्थान उपयोग करें',
    askPlaceholder: 'WeatherGPT से पूछें (उदा. "क्या कल बारिश होगी?")...',
    voiceSpeak: 'बोलें',
    voiceListening: 'सुन रहा है...',
    verified: 'सत्यापित (VERIFIED)',
    contradicted: 'गलत साबित (CONTRADICTED)',
    unverified: 'असत्यापित (UNVERIFIED)',
    officialWarning: 'आधिकारिक सरकारी चेतावनी (IMD)',
    systemRisk: 'सिस्टम मौसम जोखिम (नियम-आधारित)',
    disclaimer: 'प्रोटोटाइप जोखिम स्तर सलाहकारी हैं और आधिकारिक चिकित्सा या सरकारी मानक नहीं हैं।',
  },
  ta: {
    navChat: 'உரையாடல் உதவியாளர்',
    navForecast: 'வானிலை முன்னறிவிப்பு',
    navWhatIf: 'சூழ்நிலை பகுப்பாய்வு',
    navAlerts: 'எச்சரிக்கை மையம்',
    navVerify: 'செய்தி உண்மை சரிபார்ப்பு',
    navClimate: 'காலநிலை போக்குகள்',
    navProviders: 'வானிலை சேவைகள்',
    currentWeather: 'தற்போதைய வானிலை',
    feelsLike: 'உணரும் வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    wind: 'காற்று வேகம்',
    pressure: 'காற்று அழுத்தம்',
    visibility: 'பார்வைத்திறன்',
    sunrise: 'சூரிய உதயம்',
    sunset: 'சூரிய அஸ்தமனம்',
    searchCity: 'நகரத்தைத் தேடுங்கள் (எ.கா. சென்னை, மதுரை)...',
    useGps: 'தற்போதைய இருப்பிடம்',
    askPlaceholder: 'வானிலை கேள்விகள் கேட்கவும் (எ.கா. "நாளைக்கு மழை வருமா?")...',
    voiceSpeak: 'பேசுங்கள்',
    voiceListening: 'கேட்கிறது...',
    verified: 'சரிபார்க்கப்பட்டது (VERIFIED)',
    contradicted: 'முரணானது (CONTRADICTED)',
    unverified: 'உறுதிப்படுத்தப்படவில்லை (UNVERIFIED)',
    officialWarning: 'அதிகாரப்பூர்வ அரசு எச்சரிக்கை (IMD)',
    systemRisk: 'கணினி வானிலை ஆபத்து எச்சரிக்கை',
    disclaimer: 'இடர் பகுப்பாய்வு ஆலோசனை நோக்கங்களுக்கானது, இது உத்தியோகபூர்வ மருத்துவ அல்லது அரசு வழிகாட்டுதல் அல்ல.',
  }
};
